---
title: James Test
timezone: UTC
collections:
  properties:
    title: Properties
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
  values:
    completed: false
    list_image:
    list_images:
    slug:
    name:
    value:
    valuations: [],
    beds:
    baths:
    rented: false
    rent:
    rent_gross:
    rent_net:
    acquired:
    status:
    fund:
    location:
      postcode:
      longitude:
      latitude:
    rationale:
permalink: pretty
